# For development
version: "3.8"

services:
    bebtrk:
        build:
            context: .
        environment:
            BEBTRK_SERVER_DB: ${BEBTRK_DB:-bebtrk}
            BEBTRK_SERVER_DB_HOST: ${POSTGRES_HOST:-database}
            BEBTRK_SERVER_DB_USERNAME: ${POSTGRES_USER:-bebtrk}
            BEBTRK_SERVER_DB_PASSWORD: ${POSTGRES_PASSWORD:-secret}
            BEBTRK_API_KEY: ${BEBTRK_API_KEY:-dev}
        depends_on:
            - database
        ports:
            - "${BEBTRK_LISTEN:-127.0.0.1:8900}:8900"
        restart: unless-stopped

    database:
        image: postgres:16
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
            POSTGRES_USER: ${POSTGRES_USER:-bebtrk}
            POSTGRES_DB: ${POSTGRES_DB:-bebtrk}
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    pgdata:
