name: bebtrk_server
description: Sync server for bebtrk
version: 1.0.0
homepage: https://int.fish

environment:
    sdk: ^3.0.0

dependencies:
    args: ^2.4.2
    crdt_sync: ^1.0.9
    http: ^1.1.1
    postgres_crdt: ^2.1.5
    rxdart: ^0.27.7
    shelf: ^1.4.1
    shelf_router: ^1.1.4
    shelf_web_socket: ^1.0.4
    web_socket_channel: ^2.4.0
    version: ^3.0.2
    ulid: ^2.0.0

dev_dependencies:
    lints: any
    test: any
